### ISSUE TITLE
Debugging a Spry Game

### ISSUE THREAD

**Issue by primenumber59** [jasonliang-dev/spry#1]
Is the diagnostic output to the spry window in the event of an error the full extent of the debug features? I presume stepping through the written game code is not possible in ZeroBrane or similar?

**Comment by jasonliang-dev** [comment]
I've never heard of ZeroBrane before. I'm super impressed at how lightweight it is! I'll definitely take a look at solutions for step-by-step debugging now that I know there's a decent tool for that.

As of right now, yes. The ugly white text is what you'll get when you run into an error. You might even come across a scenario where the current renderer's transform matrix makes the text so large that it runs out to the right side of the window. If you find that the error is hard to read from the window, the error is also printed to the console. On Windows, console output isn't available by default and you'll need to set `console_attach` to `true` in `spry.conf`.

**Comment by primenumber59** [comment]
Thank you for the reply and tip about the console on Windows. The Spry framework looks very useful, so thanks for making it available.

**Comment by jasonliang-dev** [comment]
Some updates on this:
- `console_attach` is now `win_console`. You can also use the `--console` command line argument.
- I crudely added LuaSocket support which will be in the next release. MobDebug (and in turn, ZeroBrane) uses it for debugging.

![Screenshot 2023-11-23 181153](https://github.com/jasonliang-dev/spry/assets/16218676/6e523a82-f3ea-4d0b-b94d-723ea028e180)

It's now possible to debug using ZeroBrane, but there's still more work to be done:
- Projects should have a way to toggle MobDebug on/off. Love2D projects use a `-debug` argument to do this. It's currently not possible to read command line arguments from Lua scripts.
- LuaSocket modules have to be copied over into the project directory. Users shouldn't have to do this.

I'll try to support ZeroBrane once the LuaSocket stuff is fleshed out. Alternatively, you can use VS Code with the [Local Lua Debugger](https://marketplace.visualstudio.com/items?itemName=tomblind.local-lua-debugger-vscode) extension for step-by-step debugging.

**Comment by primenumber59** [comment]
This is excellent! I am still at the beginning of my journey with Spry, but knowing that there will be more than the console for diagnosing issues (and the speed you are working on what is a pet project) is confidence boosting. Supporting ZeroBrane (since it is a Lua IDE) can only be a good thing.

**Comment by jasonliang-dev** [comment]
I just released a new version of Spry with proper LuaSocket support and the ability to read command line arguments from Lua. This means you can now debug with ZeroBrane :)

Look at the [Debugging](https://jasonliang.js.org/spry/debugging.html) guide for details. I'll be closing this now. Feel free to reopen and/or reply if there's anything else.
