### ISSUE TITLE
A contains function?

### ISSUE THREAD

**Issue by primenumber59** [jasonliang-dev/spry#2]
I don't want to encourage feature-creep, but in the Utility functions, the first function I missed was a _contains_ that returns true when a point is in a rectangular region.
 
contains(x0, y0, x1, y1, xP, yP)

while the user can add it, I was expecting to see it built-in?

**Comment by jasonliang-dev** [comment]
Added `aabb_overlap` and `rect_overlap`. These functions act as rectangle vs point instead of rectangle vs rectangle when the last two arguments are omitted.

**Comment by primenumber59** [comment]
They both sound like great additions. I can't help with coding, but if you had a Ko-fi or similar, I would buy you a coffee.

**Comment by jasonliang-dev** [comment]
I don't have a Ko-fi. Just the fact that someone else is benefiting from this project is enough!
