### ISSUE TITLE
The dungeon and networking examples incorrectly call co_resume 

### ISSUE THREAD

**Issue by primenumber59** [jasonliang-dev/spry#4]
In these files:

examples\dungeon\chort.lua
examples\dungeon\coinlua
examples\dungeon\player.lua
examples\networking\client\main.lua

_co_resume_ need to be replaced with _resume_.

**Comment by jasonliang-dev** [comment]
`co_resume` is actually correct. It was renamed while adding multithreading support. The latest release and the website docs aren't caught up with the current source.

I'll probably reverse the change.

**Comment by primenumber59** [comment]
~~Ah I see! In that case it would be handy if the latest version download from here:~~

~~https://github.com/jasonliang-dev/spry/releases~~

~~also included a zip file with all the examples that work with it. That way, while the source is worked on, there is a separate set of examples that are compatible with the executable version that is downloaded.~~

**Comment by primenumber59** [comment]
Please ignore my previous comment, I just realised that the source code zip file is exactly what I need and am talking about.

I am not a knowledgeable github user, and this is the first time I have got involved like this and am making mistakes and learning as I go.
