### ISSUE TITLE
Is the z-order of the World object consistent or indeterminate?

### ISSUE THREAD

**Issue by primenumber59** [jasonliang-dev/spry#5]
I have presumed that the World z-order works so that objects added later are closer to the front. Is that the case, or is it indeterminate?

When adding my own objects to the World in the code below, the z-order of the buttons is not what I thought as shown in this image. But I found that when the CentreText (one of my objects) is _not_ added to the World, by commenting out the line, the buttons appear in front of the rectangle.

Can you please explain how the World z-order works, and how can not including a single object affect the order of the objects added later?

I have zipped up the project folder and attached it.

![image](https://github.com/jasonliang-dev/spry/assets/58136499/1ffd4b5d-cb51-463c-b4cf-0b08fb8ba39a)

```
function spry.conf(t)
  t.window_width = 640
  t.window_height = 480
end

function spry.start(arg)
  gWorld = World()

  gTitleFont = spry.font_load 'Roboto-Black.ttf'
  -- if the next line is commented out, all three buttons appear in front of the StoryText rectangle
  gTitle = gWorld:add(CentreText(10,'My Game',gTitleFont,48,255,255,255))

  gStorytext = gWorld:add(StoryText(50, 100, 540, 310, 'Roboto-Black.ttf', 20))
  gStorytext:setText('Hello!')

  gButtonPlay = gWorld:add(Button(10,400,100,24,'Play'))
  gButtonSettings = gWorld:add(Button(300,400,100,24,'Settings'))
  gButtonQuit = gWorld:add(Button(500,400,100,24,'Quit'))
end

function spry.frame(dt)
  gWorld:update(dt)
  gWorld:draw()
end
```
[testzorder.zip](https://github.com/jasonliang-dev/spry/files/14003111/testzorder.zip)

**Comment by jasonliang-dev** [comment]
All world objects have a `z_index`. Objects are drawn back to front, sorted by the smallest `z_index` to the largest. If two objects have the same z-index, the order is undefined.

The default z-index value is 0. To draw the buttons in front StoryText, set the z-index to something greater than 0:

```lua
function Button:new(...)
  self.z_index = 10
  -- the rest of button's constructor...
end
```

Alternatively, you can move StoryText behind the buttons:

```lua
function StoryText:new(...)
  self.z_index = -1
  -- ...
end
```

**Comment by primenumber59** [comment]
I was assuming that the z-index is implicitly getting increased for each object added to the World. But now I know that each one is zero, unless set otherwise with the z_index property, that all makes sense, thank you.
